"use client";

import {
  Network,
  Layers,
  Brain,
  Calculator,
  SlidersHorizontal,
  AlertTriangle,
  ArrowRight,
} from "lucide-react";

/* ================================================================== */
/*  Section data                                                       */
/* ================================================================== */

const ENCODER_FILTERS = [32, 64, 128, 256, 512] as const;

const LIMITATIONS = [
  {
    label: "Domain Shift",
    body: "The model is sensitive to variations in H&E staining protocols across different hospitals and scanners. A slide stained with a slightly different eosin concentration or digitized on a different whole-slide imager can shift the color distribution enough to degrade predictions. Without stain-normalization or fine-tuning, out-of-distribution slides may produce unreliable maps.",
  },
  {
    label: "Biological Ambiguity",
    body: "Some protein markers do not produce consistent morphological changes visible on H&E. In these cases the model may rely on spatial bias — for example, predicting a marker as positive simply because it tends to appear in stromal regions — rather than learning a true morphological correlate.",
  },
  {
    label: "Ground Truth Ceiling",
    body: "The model is trained to replicate multiplex immunofluorescence (mIF) annotations generated by fluorescent antibodies. Any noise, non-specific binding, or registration error in the original mIF ground truth is learned by the network. The model cannot exceed the quality of its training labels.",
  },
  {
    label: "Hallucinations",
    body: "Tissue artifacts such as folds, tears, pen marks, air bubbles, and necrotic debris can produce confident false-positive predictions. The network has limited ability to distinguish artifact texture from genuine cellular morphology, especially when the artifact pattern overlaps with learned features.",
  },
] as const;

/* ================================================================== */
/*  Reusable sub-components                                            */
/* ================================================================== */

function SectionHeader({
  icon,
  title,
  accentColor,
}: {
  icon: React.ReactNode;
  title: string;
  accentColor: string;
}) {
  return (
    <div className="flex items-center gap-2.5 mb-4">
      <span
        className="flex items-center justify-center w-8 h-8 rounded-lg"
        style={{ backgroundColor: `${accentColor}22` }}
      >
        {icon}
      </span>
      <h2 className="text-lg font-bold">{title}</h2>
    </div>
  );
}

/** Render a formula row — label on left, "equation" on right */
function FormulaRow({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col sm:flex-row sm:items-start gap-1 sm:gap-4 py-2 border-b border-[var(--card-border)] last:border-0">
      <span className="text-xs font-semibold text-[var(--accent)] shrink-0 w-36">
        {label}
      </span>
      <span className="text-sm font-mono text-[var(--foreground)]/80 leading-relaxed break-words">
        {children}
      </span>
    </div>
  );
}

/* ================================================================== */
/*  Page                                                               */
/* ================================================================== */

export default function MethodologyPage() {
  return (
    <div className="max-w-4xl mx-auto">
      {/* ── Page header ── */}
      <h1 className="text-2xl font-bold mb-1">Methodology</h1>
      <p className="text-sm text-[var(--muted)] mb-8">
        A transparent look at GigaTIME&apos;s deep-learning pipeline — architecture,
        training math, biological assumptions, and known limitations.
      </p>

      {/* ================================================================ */}
      {/* Section A — Deep Learning Architecture                           */}
      {/* ================================================================ */}
      <section
        className="card mb-8"
        style={{ borderLeft: "3px solid #4dabf7" }}
      >
        <SectionHeader
          icon={<Network className="w-5 h-5 text-blue-400" />}
          title="Deep Learning Architecture"
          accentColor="#4dabf7"
        />

        <div className="space-y-3 text-sm text-[var(--foreground)]/80 leading-relaxed">
          <p>
            GigaTIME is built on{" "}
            <span className="font-semibold text-[var(--accent)]">
              UNet++ (Nested U-Net)
            </span>
            , an encoder–decoder architecture with dense skip connections designed
            for biomedical image segmentation.
          </p>

          <p>
            The <strong>encoder</strong> follows a VGG-style design: at each of the
            five levels, a <em>VGGBlock</em> applies two consecutive{" "}
            <code className="text-xs bg-white/5 px-1 rounded">
              Conv2d(3×3) → BatchNorm → ReLU
            </code>{" "}
            layers. The filter widths double at each level:
          </p>

          {/* filter-level diagram */}
          <div className="flex flex-wrap items-center gap-2 py-2">
            {ENCODER_FILTERS.map((f, i) => (
              <div key={f} className="flex items-center gap-2">
                <span className="px-3 py-1.5 rounded-md bg-blue-500/15 text-blue-300 text-xs font-mono font-bold">
                  {f}
                </span>
                {i < ENCODER_FILTERS.length - 1 && (
                  <ArrowRight className="w-3.5 h-3.5 text-[var(--muted)]" />
                )}
              </div>
            ))}
          </div>

          <p>
            <strong>Downsampling</strong> uses{" "}
            <code className="text-xs bg-white/5 px-1 rounded">
              MaxPool2d(2, 2)
            </code>
            ; <strong>upsampling</strong> uses bilinear interpolation (
            <code className="text-xs bg-white/5 px-1 rounded">
              Upsample(scale_factor=2, mode=&apos;bilinear&apos;)
            </code>
            ).
          </p>

          <p>
            Unlike a standard U-Net, UNet++ introduces <strong>dense skip
            connections</strong>: every intermediate decoder node X<sup>i,j</sup>{" "}
            receives concatenated features from all prior same-level nodes
            (X<sup>i,0</sup> … X<sup>i,j−1</sup>) plus the upsampled feature map
            from the level below. This allows the network to learn fine-grained and
            high-level tissue features simultaneously.
          </p>

          <p>
            The <strong>final layer</strong> is a{" "}
            <code className="text-xs bg-white/5 px-1 rounded">
              Conv2d(32 → 23, kernel_size=1)
            </code>{" "}
            — a 1×1 convolution that produces <strong>23 logit maps</strong> (one
            per protein channel). A{" "}
            <span className="font-semibold text-[var(--accent)]">
              Sigmoid activation
            </span>{" "}
            is applied at inference time to convert logits into probability maps in
            the range [0, 1].
          </p>
        </div>
      </section>

      {/* ================================================================ */}
      {/* Section B — Ground Truth & Slide Registration                    */}
      {/* ================================================================ */}
      <section
        className="card mb-8"
        style={{ borderLeft: "3px solid #40c057" }}
      >
        <SectionHeader
          icon={<Layers className="w-5 h-5 text-emerald-400" />}
          title="Ground Truth & Slide Registration"
          accentColor="#40c057"
        />

        <div className="space-y-3 text-sm text-[var(--foreground)]/80 leading-relaxed">
          <p>
            Training a virtual staining model requires <em>paired</em> data: the
            same tissue region imaged with both H&amp;E and multiplex
            immunofluorescence (mIF). Because a single tissue section cannot be
            stained twice, GigaTIME relies on two key techniques:
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-2">
            {/* Serial Sectioning */}
            <div className="p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
              <h3 className="text-sm font-bold text-emerald-400 mb-1.5">
                Serial Sectioning
              </h3>
              <p className="text-xs text-[var(--foreground)]/70 leading-relaxed">
                Two consecutive 4-µm slices are cut from the same tissue block.
                One section is stained with H&amp;E (the model&apos;s input); the
                adjacent section is stained with a multiplex panel of fluorescent
                antibodies (COMET), producing the ground-truth protein maps the
                model learns to predict.
              </p>
            </div>

            {/* Elastic Registration */}
            <div className="p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
              <h3 className="text-sm font-bold text-emerald-400 mb-1.5">
                Elastic Registration
              </h3>
              <p className="text-xs text-[var(--foreground)]/70 leading-relaxed">
                Because consecutive slices are not identical (tissue deforms
                during cutting and mounting), an{" "}
                <strong className="text-emerald-300">
                  elastic registration
                </strong>{" "}
                algorithm warps the mIF section to align pixel-to-pixel with the
                H&amp;E section. This non-rigid transformation accounts for
                local stretching, compression, and rotation so that each H&amp;E
                pixel has a precisely matched mIF ground-truth label.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ================================================================ */}
      {/* Section C — The Biological Hypothesis (callout)                  */}
      {/* ================================================================ */}
      <section className="mb-8 rounded-xl bg-purple-500/10 border border-purple-500/25 p-5">
        <SectionHeader
          icon={<Brain className="w-5 h-5 text-purple-400" />}
          title="The Biological Hypothesis"
          accentColor="#a855f7"
        />

        <blockquote className="text-sm text-purple-200/80 leading-relaxed italic space-y-3">
          <p>
            How can an AI &ldquo;see&rdquo; proteins that are invisible on a standard
            H&amp;E stain?
          </p>
          <p>
            The core hypothesis is that a cell&apos;s <strong className="text-purple-300 not-italic">molecular state</strong>{" "}
            — which proteins it expresses and at what level — forces subtle but
            systematic physical changes in its <strong className="text-purple-300 not-italic">
            nuclear morphology</strong>, chromatin texture, and cytoplasmic
            structure. A CD8+ cytotoxic T cell, for example, has a characteristically
            compact, round nucleus that looks different from a CD68+ macrophage&apos;s
            irregular, kidney-shaped nucleus, even under plain H&amp;E.
          </p>
          <p>
            The convolutional neural network learns to detect these{" "}
            <strong className="text-purple-300 not-italic">
              morphological proxies
            </strong>{" "}
            — texture patterns, nuclear size distributions, spatial arrangements,
            and staining densities — that correlate with specific protein
            expression. It does not &ldquo;see&rdquo; the proteins directly; it infers
            their likely presence from the physical consequences of expression.
          </p>
        </blockquote>
      </section>

      {/* ================================================================ */}
      {/* Section D — Loss Functions & Training Math                       */}
      {/* ================================================================ */}
      <section
        className="card mb-8"
        style={{ borderLeft: "3px solid #fab005" }}
      >
        <SectionHeader
          icon={<Calculator className="w-5 h-5 text-amber-400" />}
          title="Loss Functions & Training Math"
          accentColor="#fab005"
        />

        <div className="space-y-4 text-sm text-[var(--foreground)]/80 leading-relaxed">
          <p>
            GigaTIME is trained with a{" "}
            <span className="font-semibold text-amber-300">BCEDiceLoss</span> — a
            composite objective that balances pixel-wise classification accuracy with
            region-level overlap:
          </p>

          {/* Combined loss */}
          <div className="rounded-lg bg-amber-500/10 border border-amber-500/20 p-4 space-y-1">
            <FormulaRow label="Combined Loss">
              <span className="italic">L</span> = 0.5 · BCE +{" "}
              <span className="italic">DiceLoss</span>
            </FormulaRow>

            <FormulaRow label="Binary Cross-Entropy">
              BCE = −(1/<span className="italic">N</span>) Σ<sub>i</sub> [
              <span className="italic"> g</span>
              <sub>i</sub> · log(σ(<span className="italic">x</span>
              <sub>i</sub>)) + (1 − <span className="italic">g</span>
              <sub>i</sub>) · log(1 − σ(<span className="italic">x</span>
              <sub>i</sub>))]
            </FormulaRow>

            <FormulaRow label="Dice per sample">
              Dice<sub>b</sub> = (2 · Σ<sub>i</sub>{" "}
              <span className="italic">p</span>
              <sub>i</sub> · <span className="italic">g</span>
              <sub>i</sub> + ε) / (Σ<sub>i</sub>{" "}
              <span className="italic">p</span>
              <sub>i</sub> + Σ<sub>i</sub>{" "}
              <span className="italic">g</span>
              <sub>i</sub> + ε)
            </FormulaRow>

            <FormulaRow label="Dice Loss">
              <span className="italic">DiceLoss</span> = 1 − (1/
              <span className="italic">B</span>) Σ
              <sub>b=1…B</sub> Dice<sub>b</sub>
            </FormulaRow>

            <FormulaRow label="Where">
              <span className="italic">p</span> = σ(logits), &nbsp;
              <span className="italic">g</span> = ground truth, &nbsp; ε = 10
              <sup>−5</sup>, &nbsp;{" "}
              <span className="italic">B</span> = batch size
            </FormulaRow>
          </div>

          <p>
            <strong>Why combine both?</strong> BCE provides stable per-pixel
            gradients that work well even for rare markers, while the Dice term
            directly optimizes the overlap metric and helps counteract class
            imbalance — ensuring the network pays attention to small positive
            regions rather than trivially predicting all-negative.
          </p>

          {/* Training config summary */}
          <div className="rounded-lg bg-[var(--background)] p-4">
            <h3 className="text-sm font-bold text-[var(--accent)] mb-3">
              Training Configuration
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-x-6 gap-y-2 text-xs">
              {[
                ["Optimizer", "Adam"],
                ["Learning Rate", "1 × 10⁻³"],
                ["Weight Decay", "1 × 10⁻⁴"],
                ["LR Schedule", "CosineAnnealing"],
                ["Min LR", "1 × 10⁻⁵"],
                ["Epochs", "100"],
                ["Batch Size", "16"],
                ["Input Size", "256 × 256 px"],
                ["Normalization", "ImageNet μ/σ"],
              ].map(([k, v]) => (
                <div key={k}>
                  <span className="text-[var(--muted)]">{k}</span>
                  <p className="font-mono font-semibold text-[var(--foreground)]/90">
                    {v}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Evaluation metrics */}
          <div>
            <h3 className="text-sm font-bold mb-2">Evaluation Metrics</h3>
            <ul className="space-y-1.5 text-xs text-[var(--foreground)]/70">
              <li className="flex items-start gap-2">
                <span className="text-amber-400 mt-0.5">•</span>
                <span>
                  <strong className="text-[var(--foreground)]/90">
                    IoU (Jaccard):
                  </strong>{" "}
                  |P ∩ G| / |P ∪ G| — intersection-over-union at the 0.5
                  probability threshold.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-amber-400 mt-0.5">•</span>
                <span>
                  <strong className="text-[var(--foreground)]/90">
                    Dice Coefficient:
                  </strong>{" "}
                  2|P ∩ G| / (|P| + |G|) — equivalent to the F1 score for
                  binary segmentation.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-amber-400 mt-0.5">•</span>
                <span>
                  <strong className="text-[var(--foreground)]/90">
                    Pearson / Spearman r:
                  </strong>{" "}
                  Correlation between predicted and true cell counts on an 8×8
                  box grid, measuring spatial-pattern agreement.
                </span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-amber-400 mt-0.5">•</span>
                <span>
                  <strong className="text-[var(--foreground)]/90">
                    Box MSE:
                  </strong>{" "}
                  Mean squared error of per-box cell counts — penalizes
                  large local deviations.
                </span>
              </li>
            </ul>
          </div>
        </div>
      </section>

      {/* ================================================================ */}
      {/* Section E — Interpreting the Features                            */}
      {/* ================================================================ */}
      <section
        className="card mb-8"
        style={{ borderLeft: "3px solid #868e96" }}
      >
        <SectionHeader
          icon={<SlidersHorizontal className="w-5 h-5 text-gray-400" />}
          title="Interpreting the Model Output"
          accentColor="#868e96"
        />

        <div className="space-y-3 text-sm text-[var(--foreground)]/80 leading-relaxed">
          <p>
            The model outputs{" "}
            <strong>pixel-level probability maps</strong>, not biological
            fluorescence intensities. Each pixel value represents the network&apos;s
            confidence (0–1) that the corresponding protein is expressed at that
            location.
          </p>

          {/* Threshold diagram */}
          <div className="flex flex-col sm:flex-row items-stretch gap-3 my-2">
            <div className="flex-1 p-3 rounded-lg bg-[var(--background)] text-center">
              <p className="text-xs text-[var(--muted)] mb-1">Raw Output</p>
              <p className="text-lg font-mono font-bold text-[var(--accent)]">
                0.00 – 1.00
              </p>
              <p className="text-[0.68rem] text-[var(--muted)] mt-1">
                Continuous probabilities
              </p>
            </div>
            <div className="flex items-center justify-center">
              <ArrowRight className="w-5 h-5 text-[var(--muted)] rotate-90 sm:rotate-0" />
            </div>
            <div className="flex-1 p-3 rounded-lg bg-[var(--background)] text-center">
              <p className="text-xs text-[var(--muted)] mb-1">Threshold</p>
              <p className="text-lg font-mono font-bold text-amber-400">
                &gt; 0.5
              </p>
              <p className="text-[0.68rem] text-[var(--muted)] mt-1">
                Binarization rule
              </p>
            </div>
            <div className="flex items-center justify-center">
              <ArrowRight className="w-5 h-5 text-[var(--muted)] rotate-90 sm:rotate-0" />
            </div>
            <div className="flex-1 p-3 rounded-lg bg-[var(--background)] text-center">
              <p className="text-xs text-[var(--muted)] mb-1">Binary Mask</p>
              <p className="text-lg font-mono font-bold text-emerald-400">
                0 / 1
              </p>
              <p className="text-[0.68rem] text-[var(--muted)] mt-1">
                Spatial presence map
              </p>
            </div>
          </div>

          <p>
            Applying a{" "}
            <span className="font-semibold text-amber-300">
              &gt; 0.5 threshold
            </span>{" "}
            binarizes each probability map into a spatial mask where 1 =
            &ldquo;marker present&rdquo; and 0 = &ldquo;marker absent.&rdquo;
            These binary masks can then be used for cell counting by dividing
            tiles into an 8×8 grid of boxes and summing positive pixels per box.
          </p>

          <p className="text-xs text-[var(--muted)] italic">
            The 0.5 threshold is the default configured in the runtime settings.
            Researchers may adjust this value to trade off sensitivity vs.
            specificity for specific markers.
          </p>
        </div>
      </section>

      {/* ================================================================ */}
      {/* Section F — Known Limitations & Caveats                          */}
      {/* ================================================================ */}
      <section className="mb-8 rounded-xl bg-red-500/10 border border-red-500/30 p-5"
        style={{ borderLeft: "3px solid #e03131" }}
      >
        <SectionHeader
          icon={<AlertTriangle className="w-5 h-5 text-red-400" />}
          title="Known Limitations & Caveats"
          accentColor="#e03131"
        />

        <p className="text-sm text-[var(--foreground)]/70 mb-4 leading-relaxed">
          GigaTIME is a research tool, not a diagnostic device. Users should be
          aware of the following limitations when interpreting model outputs:
        </p>

        <div className="space-y-3">
          {LIMITATIONS.map((lim) => (
            <div
              key={lim.label}
              className="rounded-lg bg-red-500/5 border border-red-500/15 p-3"
            >
              <h3 className="text-sm font-bold text-red-400 mb-1">
                {lim.label}
              </h3>
              <p className="text-xs text-[var(--foreground)]/70 leading-relaxed">
                {lim.body}
              </p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
